name: Build and deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'infrastructure/**'
      - 'README.md'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [ build ]
    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download wait-for-it.sh
        run: |
          curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh

      - name: Build and start test environment
        env:
          APP_ENV: TEST
        run: |
          docker compose -f ./compose/development/docker-compose.yml up --build -d

      - name: Wait for API service
        run: |
          ./wait-for-it.sh localhost:8000 -t 30
        
      - name: Wait for Postgres to be ready
        run: |
          docker compose -f ./compose/development/docker-compose.yml exec db \
            bash -c "until pg_isready -U postgres; do echo 'Waiting for DB...'; sleep 1; done"

      - name: Migrate database
        run: |
          docker compose -f ./compose/development/docker-compose.yml exec tabs-api \
            alembic -c app/db/migrations/alembic.ini upgrade head

      - name: Seed database
        run: |
          docker compose -f ./compose/development/docker-compose.yml exec tabs-api \
            python -m app.db.seed.seed_tab_data

      - name: Run API unit tests
        run: | 
          docker compose -f ./compose/development/docker-compose.yml exec tabs-api \
            pytest

      - name: Install Playwright
        run: |
          cd client
          npm ci
          npx playwright install

      - name: Run E2E tests
        run: |
          cd client
          npx playwright test --workers=1

      - name: Tear down test environment
        run: docker compose -f ./compose/development/docker-compose.yml down

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure CLI login
        run: |
          az login \
            --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker login to ACR
        run: |
          docker login ${{ secrets.ACR_LOGIN_SERVER }} \
            -u ${{ secrets.ACR_USERNAME }} \
            -p ${{ secrets.ACR_PASSWORD }}

      - name: Build proxy Docker image and push to container registry
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.ACR_LOGIN_SERVER }}/proxy:latest --push ./proxy/production

      - name: Build client Docker image and push to container registry
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.ACR_LOGIN_SERVER }}/client:latest --push ./client

      - name: Build tabs api Docker image and push to container registry
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.ACR_LOGIN_SERVER }}/tabs-api:latest --push ./tabs-api

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, tests]
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible python3-boto3 sshpass

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}
      
      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          ansible-playbook \
            -i ./infrastructure/ansible/hosts.ini \
            ./infrastructure/ansible/playbooks/deploy_app.yml