name: Build and deploy

on:
  push:
    branches: [ main ]

jobs:

  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   needs: whitelist_ssh
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Log in to DigitalOcean Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: registry.digitalocean.com
  #         username: doctl
  #         password: ${{ secrets.DO_API_TOKEN }}

  #     - name: Build proxy Docker image and push to container registry
  #       run: |
  #         docker buildx build --platform linux/amd64 -t registry.digitalocean.com/guitar-tabs-registry/app:proxy-latest --push ./proxy/production

  #     - name: Build client Docker image and push to container registry
  #       run: |
  #         docker buildx build --platform linux/amd64 -t registry.digitalocean.com/guitar-tabs-registry/app:client-latest --push ./client

  #     - name: Build tabs api Docker image and push to container registry
  #       run: |
  #         docker buildx build --platform linux/amd64 -t registry.digitalocean.com/guitar-tabs-registry/app:tabs-api-latest --push ./tabs-api

  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start test environment
        run: |
          docker compose -f ./compose/docker-compose.yml up --build -d

      - name: Wait for services
        run: |
          ./scripts/wait-for-it.sh localhost:8000 -t 30

      - name: Install Playwrite
        run: |
          cd client
          npm ci
          npx playwright install

      - name: Run E2E tests
        run: |
          cd client
          npx playwright test --workers=1

      - name: Tear down test environment
        run: docker compose -f ./compose/docker-compose.yml down

  deploy:
    name: Deploy with Ansible
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible python3-boto3 sshpass

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}
      
      - name: Add host to known_hosts
        run: ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          ansible-playbook \
            -i ./infrastructure/ansible/hosts.ini \
            ./infrastructure/ansible/playbooks/deploy.yml