name: Build and deploy

on:
  push:
    branches: [ main, sonarqube ]
    paths-ignore:
      - 'infrastructure/**'
      - 'README.md'

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9 #v7.0.0
        env:
          SONAR_LOGIN_KEY: ${{ secrets.SONAR_LOGIN_KEY }}
 